### ISSUE TITLE
Move verification test into this repo

### ISSUE THREAD

**Issue by jackkleeman** [restatedev/e2e#118]
```[tasklist]
### Tasks
- [ ] https://github.com/restatedev/e2e/issues/122
- [x] Produce the verification docker image from this repo
- [x] Archive the old verification service repo
```

cc @tillrohrmann
