### ISSUE TITLE
Missing e2e tests for Typescript SDK

### ISSUE THREAD

**Issue by tillrohrmann** [restatedev/e2e#120]
This is an umbrella issue capturing the missing e2e tests for the Typescript SDK.

```[tasklist]
### Tasks
- [ ] #108
- [ ] Add test for https://github.com/restatedev/sdk-typescript/issues/21
- [ ] https://github.com/restatedev/e2e/issues/129
- [x] Check whether there is an e2e test for the new failure semantics
```
